### ISSUE TITLE
Error on clear_team route

### ISSUE THREAD

**Issue by horozco** [EdgarOrtegaRamirez/lita-team#3]
The route REGEX in the clear_team.rb handler should contains an end of line symbol `$`.

**Comment by jcabasc** [comment]
Please, go ahead and create a PR. Come on, you got this. 🎱

**Comment by horozco** [comment]
Just created a PR for this issue: https://github.com/EdgarOrtegaRamirez/lita-team/pull/5

@EdgarOrtegaRamirez  please take a look.
